version: '3.8'

services:
  backend:
    image: puffoide/fs3-foro-ms:latest
    container_name: foro-backend
    ports:
      - "8080:8080"
    environment:
      TNS_ADMIN: /app/wallet
    networks:
      - foro-net

  frontend:
    image: puffoide/fs3-foro-app:latest
    container_name: foro-frontend
    ports:
      - "4200:80"
    networks:
      - foro-net
    depends_on:
      - backend

networks:
  foro-net:
